# Generated by Django 5.2.7 on 2025-11-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="owner",
        ),
    ]
