# Generated by Django 5.2.7 on 2025-11-16 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.date(2000, 1, 1),
                help_text="Введите дату рождения",
                verbose_name="Дата рождения",
            ),
            preserve_default=False,
        ),
    ]
